In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Reading the Dataset
dataset = pd.read_csv('CKD.csv')

In [3]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [6]:
#It will be a list containing the column names of your dataset
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [7]:
indep=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
dep=dataset['classification_yes']

In [8]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_= sc.fit_transform(X_train)
X_test_= sc.transform(X_test)

In [10]:
from sklearn.ensemble import RandomForestClassifier

In [11]:
from sklearn.model_selection import GridSearchCV

param_grid = {'criterion':['gini','entropy'],
              'max_features': ['auto','sqrt','log2'],
              'n_estimators':[10,100]} 



grid = GridSearchCV(RandomForestClassifier(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1') 
   
# fitting the model for grid search 
grid.fit(X_train_, y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

GridSearchCV(estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             scoring='f1', verbose=3)

In [12]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test_) 
   
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)

# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [13]:
print(grid.best_params_)

{'criterion': 'entropy', 'max_features': 'sqrt', 'n_estimators': 100}

In [14]:
table=pd.DataFrame.from_dict(re)

In [18]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.042591,0.002963,0.007438,0.001016,gini,auto,10,"{'criterion': 'gini', 'max_features': 'auto', ...",0.800000,0.810811,0.790698,0.871795,0.857143,0.826089,0.032311,9
1,0.494834,0.070929,0.033551,0.002310,gini,auto,100,"{'criterion': 'gini', 'max_features': 'auto', ...",0.800000,0.871795,0.809524,0.900000,0.923077,0.860879,0.048707,1
2,0.058957,0.009980,0.011077,0.003550,gini,sqrt,10,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.800000,0.871795,0.809524,0.842105,0.914286,0.847542,0.041900,7
3,0.572304,0.034479,0.038371,0.004922,gini,sqrt,100,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.800000,0.842105,0.809524,0.900000,0.923077,0.854941,0.048824,5
4,0.068016,0.014126,0.007182,0.001164,gini,log2,10,"{'criterion': 'gini', 'max_features': 'log2', ...",0.645161,0.777778,0.769231,0.923077,0.864865,0.796022,0.094543,12
5,0.503372,0.039768,0.035808,0.002791,gini,log2,100,"{'criterion': 'gini', 'max_features': 'log2', ...",0.800000,0.820513,0.809524,0.926829,0.923077,0.855989,0.056695,3
6,0.062018,0.007161,0.013423,0.009252,entropy,auto,10,"{'criterion': 'entropy', 'max_features': 'auto...",0.727273,0.777778,0.780488,0.926829,0.882353,0.818944,0.073807,10
7,0.552799,0.070595,0.038858,0.007902,entropy,auto,100,"{'criterion': 'entropy', 'max_features': 'auto...",0.800000,0.820513,0.809524,0.900000,0.923077,0.850623,0.050688,6
8,0.086236,0.018127,0.015810,0.009413,entropy,sqrt,10,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.727273,0.777778,0.750000,0.871795,0.944444,0.814258,0.081591,11
9,0.503694,0.044818,0.039409,0.008394,entropy,sqrt,100,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.800000,0.820513,0.809524,0.900000,0.947368,0.855481,0.058031,4
10,0.067387,0.010912,0.014709,0.009295,entropy,log2,10,"{'criterion': 'entropy', 'max_features': 'log2...",0.833333,0.789474,0.837209,0.871795,0.888889,0.844140,0.034411,8
11,0.486200,0.007610,0.032245,0.004027,entropy,log2,100,"{'criterion': 'entropy', 'max_features': 'log2...",0.800000,0.871795,0.809524,0.900000,0.923077,0.860879,0.048707,1

In [15]:

from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'criterion': 'entropy', 'max_features': 'sqrt', 'n_estimators': 100}: 0.9849624060150376

In [16]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[50  1]
 [ 1 81]]

In [17]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       0.98      0.98      0.98        51
           1       0.99      0.99      0.99        82

    accuracy                           0.98       133
   macro avg       0.98      0.98      0.98       133
weighted avg       0.98      0.98      0.98       133

In [20]:
table_pr=pd.DataFrame()

In [21]:
print(X_test)

           age     bp   al   su         bgr    bu   sc         sod       pot  \
132  46.000000   70.0  0.0  0.0  100.000000  47.0  0.5  142.000000  3.500000
309  66.000000   90.0  2.0  0.0  153.000000  76.0  3.3  137.528754  4.627244
334  69.000000   70.0  0.0  0.0   83.000000  42.0  1.2  139.000000  3.700000
196  55.000000  100.0  1.0  4.0  297.000000  53.0  2.8  139.000000  4.500000
246  60.000000   90.0  2.0  0.0  105.000000  53.0  2.3  136.000000  5.200000
..         ...    ...  ...  ...         ...   ...  ...         ...       ...
349  71.000000   70.0  0.0  0.0   81.000000  18.0  0.8  145.000000  5.000000
168  50.000000   80.0  0.0  0.0  137.000000  46.0  0.8  139.000000  5.000000
150  48.000000  100.0  0.0  0.0  103.000000  79.0  5.3  135.000000  6.300000
392  51.492308   60.0  3.0  0.0  148.112676  34.0  1.2  137.528754  4.627244
66   34.000000   60.0  0.0  0.0   91.000000  49.0  1.2  135.000000  4.500000

          hrmo  ...  rbc_normal  pc_normal  pcc_present  ba_present  htn_yes  \
132  16.400000  ...           1          1            0           0        0
309  12.518156  ...           1          1            0           1        0
334  16.200000  ...           1          1            0           0        0
196  11.200000  ...           1          1            0           0        1
246  11.100000  ...           0          1            0           0        0
..         ...  ...         ...        ...          ...         ...      ...
349  14.700000  ...           1          1            0           0        0
168  14.100000  ...           1          1            0           0        0
150   6.300000  ...           1          1            0           0        1
392  10.800000  ...           0          0            0           0        0
66   13.500000  ...           1          1            0           0        0

     dm_yes  cad_yes  appet_yes  pe_yes  ane_yes
132       0        0          1       0        0
309       0        0          0       0        0
334       0        0          1       0        0
196       1        0          1       0        0
246       0        0          1       0        0
..      ...      ...        ...     ...      ...
349       0        0          1       0        0
168       0        0          1       0        0
150       0        1          0       0        0
392       0        0          1       0        0
66        0        0          1       0        0

[133 rows x 27 columns]

In [22]:
table_pr.head(134)

Empty DataFrame
Columns: []
Index: []

In [25]:
table_pr.to_csv("cm.csv",index=False)